### ISSUE TITLE
Missing license and copyright notice

### ISSUE THREAD

**Issue by khuedoan** [coolface88/iac-lab#1]
This repository is a derivative work of my [khuedoan/homelab](https://github.com/khuedoan/homelab) project, which is licensed under the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html) license, therefore your repository must:

- [x] Be open-source
- [ ] Includes [GPLv3 license](https://github.com/khuedoan/homelab/blob/master/LICENSE.md)
- [x] Includes [copyright notice](https://github.com/khuedoan/homelab#license) and/or an acknowledgement in the `README` file

Thanks!

**Comment by coolface88** [comment]
Hi @khuedoan thanks and sorry about that. I should have credited you. I just want to do some self-learning and demo to the team. Anyway I will reference you on README.

**Comment by khuedoan** [comment]
Thanks :smile:

**Comment by khuedoan** [comment]
Btw you can add the license from GitHub UI or copy from my repo

**Comment by khuedoan** [comment]
Hi @coolface88, any update on the license?
